name: Compile bdk-jvm For All Targets
on: [workflow_dispatch]

permissions: {}

jobs:
  build-macOS-native-libs:
    name: "Create M1 and x86_64 native binaries"
    runs-on: macos-14
    steps:
      - name: "Checkout publishing branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build bdk-jvm library"
        run: |
          bash ./scripts/build-macos-aarch64.sh
          bash ./scripts/build-macos-x86_64.sh

      - name: "Upload macOS native libraries"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos
          path: /Users/runner/work/bdk-jvm/bdk-jvm/lib/src/main/resources/

  build-windows-native-lib:
    name: "Create Windows native binaries"
    runs-on: windows-2022
    steps:
      - name: "Checkout publishing branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build bdk-jvm library"
        run: bash ./scripts/build-windows-x86_64.sh

      - name: "Upload Windows native libraries"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          path: D:\a\bdk-jvm\bdk-jvm\lib\src\main\resources\

  build-full-library:
    name: Create full bdk-jvm library
    needs: [build-macOS-native-libs, build-windows-native-lib]
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout publishing branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build bdk-jvm library"
        run: bash ./scripts/build-linux-x86_64.sh

      - name: "Download macOS native binaries from previous job"
        uses: actions/download-artifact@v4
        with:
          name: artifact-macos
          path: ./bdk-jvm/lib/src/main/resources/

      - name: "Download Windows native libraries from previous job"
        uses: actions/download-artifact@v4
        with:
          name: artifact-windows
          path: ./bdk-jvm/lib/src/main/resources/

      - name: "Upload library code and binaries"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-full
          path: ./bdk-jvm/lib/
