name: Trigger Tests for BDK-FFI Latest Commit
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-bdk-jvm-test ]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Update bdk-ffi submodule to latest"
        run: |
          cd ./bdk-ffi/ \
          && git fetch origin \
          && git checkout master \
          && git pull origin master \
          && echo "Testing commit: $(git log -1 --pretty=format:'%h %s (author: %an)')"

      - name: "Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Run JVM tests"
        run: |
          bash ./scripts/build-linux-x86_64.sh --skip-submodule-update
          ./gradlew test -P excludeConnectedTests
          ./gradlew :examples:build
